# Generated by Django 4.2.7 on 2023-11-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0002_remove_user_password_row_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=125),
        ),
    ]
