# Generated by Django 4.2.7 on 2023-11-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=38, verbose_name='Электронный адрес почты')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Расход'), (2, 'Доход')])),
                ('reason', models.CharField(max_length=60, verbose_name='Причина')),
                ('price', models.IntegerField(verbose_name='Финансовая стоимость')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.user', verbose_name='Пользователь')),
            ],
        ),
    ]
