# Generated by Django 4.2.7 on 2023-11-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_r',
            new_name='password_row',
        ),
    ]
