# Generated by Django 4.2.7 on 2023-11-22 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0003_rename_password_r_user_password_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='price',
        ),
        migrations.AddField(
            model_name='operations',
            name='amount',
            field=models.IntegerField(default=5, verbose_name='Финансовая стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=models.IntegerField(choices=[(1, 'Росход'), (2, 'Доход')], verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='reason',
            field=models.CharField(max_length=75, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ползователь'),
        ),
    ]
