# Generated by Django 4.2.7 on 2023-11-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0008_operations_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=123, unique=True),
        ),
    ]
