# Generated by Django 4.2.7 on 2023-11-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0009_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Новая категория:'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bc.category', verbose_name='Категория'),
        ),
    ]
