# Generated by Django 4.2.7 on 2023-11-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0011_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=125, unique=True, verbose_name='Новая категория:'),
        ),
    ]
