# Generated by Django 4.2.7 on 2023-11-23 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0012_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=' ', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Название категории:'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bc.category', verbose_name='Категория'),
        ),
    ]
