# Generated by Django 4.2.7 on 2023-11-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0013_alter_category_slug_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=125, unique=True, verbose_name='Название категории:'),
        ),
    ]
