# Generated by Django 4.2.7 on 2023-11-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0014_alter_category_slug_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=125, verbose_name='Название категории:'),
        ),
    ]
