# Generated by Django 4.2.7 on 2023-11-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0015_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
