# Generated by Django 4.2.7 on 2023-11-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0016_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='type',
            new_name='typ',
        ),
    ]
